link_rails_tut: http://www.railstutorial.org/
help: http://www.railstutorial.org/help
book: http://www.railstutorial.org/book
home: http://www.railstutorial.org/home
ct: http://www.railstutorial.org/contact
ruby: http://rubyonrails.org/
ss: http://screencasts.railstutorial.org/
ror: http://rubyonrails.org/
news: http://news.railstutorial.org/
michaelhartl: http://www.michaelhartl.com/
en: en
vi: vi
cat: http://rubyonrails.org/
max50: 50
max255: 255
min6: 6
regex_mail: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
